export default {
  title: 'Atajos de teclado',
  devConsole: 'Abrir/cerrar consola de desarrollo',
  devConsoleShortcut: 'Shift + T',
  sendMessage: 'Enviar mensaje',
  sendMessageShortcut: 'Enter',
  newLine: 'Nueva línea',
  newLineShortcut: 'Shift + Enter',
  focusInput: 'Foco en el área de entrada',
  focusInputShortcut: 'Ctrl + /',
  showAll: 'Mostrar header, chat y config sidebar',
  showAllShortcut: 'Shift + A',
  toggleConfigSidebar: 'Abrir/cerrar config sidebar',
  toggleConfigSidebarShortcut: 'Shift + X',
  toggleChatSidebar: 'Abrir/cerrar chat sidebar',
  toggleChatSidebarShortcut: 'Shift + C',
  toggleHeader: 'Abrir/cerrar header',
  toggleHeaderShortcut: 'Shift + H',
  closeAll: 'Cerrar todos: header, chat y config sidebar',
  closeAllShortcut: 'Shift + Q',
  newChat: 'Nueva conversación',
  newChatShortcut: 'Shift + N',
  openToolSelector: 'Activar y abrir selector de herramientas',
  openToolSelectorShortcut: 'Shift + W',
  toggleTools: 'Activa/desactiva sistema de Agentes',
  toggleToolsShortcut: 'Shift + D',
};
