export default {
  title: 'Tastenkombinationen',
  devConsole: 'Entwicklerkonsole öffnen/schließen',
  devConsoleShortcut: 'Shift + T',
  sendMessage: 'Nachricht senden',
  sendMessageShortcut: 'Enter',
  newLine: 'Neue Zeile',
  newLineShortcut: 'Shift + Enter',
  focusInput: 'Fokus auf Eingabefeld',
  focusInputShortcut: 'Ctrl + /',
  showAll: 'Header, Chat und Config Sidebar anzeigen',
  showAllShortcut: 'Shift + A',
  toggleConfigSidebar: 'Config Sidebar öffnen/schließen',
  toggleConfigSidebarShortcut: 'Shift + X',
  toggleChatSidebar: 'Chat Sidebar öffnen/schließen',
  toggleChatSidebarShortcut: 'Shift + C',
  toggleHeader: 'Header anzeigen/verbergen',
  toggleHeaderShortcut: 'Shift + H',
  closeAll: 'Header, Chat und Config Sidebar schließen',
  closeAllShortcut: 'Shift + Q',
  newChat: 'Neues Gespräch',
  newChatShortcut: 'Shift + N',
  openToolSelector: 'Tool-Selector aktivieren und öffnen',
  openToolSelectorShortcut: 'Shift + W',
  toggleTools: 'Agentensystem Aktivieren/Deaktivieren',
  toggleToolsShortcut: 'Shift + D',
};
