export default {
  title: 'Atalhos de teclado',
  devConsole: 'Abrir/fechar console de desenvolvimento',
  devConsoleShortcut: 'Shift + T',
  sendMessage: 'Enviar mensagem',
  sendMessageShortcut: 'Enter',
  newLine: 'Nova linha',
  newLineShortcut: 'Shift + Enter',
  focusInput: 'Foco na área de entrada',
  focusInputShortcut: 'Ctrl + /',
  showAll: 'Mostrar header, chat e config sidebar',
  showAllShortcut: 'Shift + A',
  toggleConfigSidebar: 'Abrir/fechar config sidebar',
  toggleConfigSidebarShortcut: 'Shift + X',
  toggleChatSidebar: 'Abrir/fechar chat sidebar',
  toggleChatSidebarShortcut: 'Shift + C',
  toggleHeader: 'Abrir/fechar header',
  toggleHeaderShortcut: 'Shift + H',
  closeAll: 'Fechar header, chat e config sidebar',
  closeAllShortcut: 'Shift + Q',
  newChat: 'Nova conversa',
  newChatShortcut: 'Shift + N',
  openToolSelector: 'Ativar e abrir seletor de ferramentas',
  openToolSelectorShortcut: 'Shift + W',
  toggleTools: 'Ativa/desativa sistema de Agentes',
  toggleToolsShortcut: 'Shift + D',
};
