export default {
  title: 'Scorciatoie da tastiera',
  devConsole: 'Apri/chiudi console di sviluppo',
  devConsoleShortcut: 'Shift + T',
  sendMessage: 'Invia messaggio',
  sendMessageShortcut: 'Enter',
  newLine: 'Nuova riga',
  newLineShortcut: 'Shift + Enter',
  focusInput: 'Focus area di input',
  focusInputShortcut: 'Ctrl + /',
  showAll: 'Mostra header, chat e config sidebar',
  showAllShortcut: 'Shift + A',
  toggleConfigSidebar: 'Apri/chiudi config sidebar',
  toggleConfigSidebarShortcut: 'Shift + X',
  toggleChatSidebar: 'Apri/chiudi chat sidebar',
  toggleChatSidebarShortcut: 'Shift + C',
  toggleHeader: 'Apri/chiudi header',
  toggleHeaderShortcut: 'Shift + H',
  closeAll: 'Chiudi header, chat e config sidebar',
  closeAllShortcut: 'Shift + Q',
  newChat: 'Nuova conversazione',
  newChatShortcut: 'Shift + N',
  openToolSelector: 'Attiva e apri selettore strumenti',
  openToolSelectorShortcut: 'Shift + W',
  toggleTools: 'Attiva/disattiva sistema Agenti',
  toggleToolsShortcut: 'Shift + D',
};
