export default {
  title: 'Keyboard Shortcuts',
  devConsole: 'Open/close Dev Console',
  devConsoleShortcut: 'Shift + T',
  sendMessage: 'Send message',
  sendMessageShortcut: 'Enter',
  newLine: 'New line',
  newLineShortcut: 'Shift + Enter',
  focusInput: 'Focus input area',
  focusInputShortcut: 'Ctrl + /',
  showAll: 'Show header, chat and config sidebar',
  showAllShortcut: 'Shift + A',
  toggleConfigSidebar: 'Toggle config sidebar',
  toggleConfigSidebarShortcut: 'Shift + X',
  toggleChatSidebar: 'Toggle chat sidebar',
  toggleChatSidebarShortcut: 'Shift + C',
  toggleHeader: 'Toggle header',
  toggleHeaderShortcut: 'Shift + H',
  closeAll: 'Close header, chat and config sidebar',
  closeAllShortcut: 'Shift + Q',
  newChat: 'New conversation',
  newChatShortcut: 'Shift + N',
  openToolSelector: 'Activate and open tool selector',
  openToolSelectorShortcut: 'Shift + W',
  toggleTools: 'Enable/disable Agents system',
  toggleToolsShortcut: 'Shift + D',
};
